{% set version = '1.2.0' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-janitor
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/janitor_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/janitor/janitor_{{ version }}.tar.gz
  sha256: 5e15a2292c65c5ddd6160289dec2604b05a813651a2be0d7854ace4548a32b8c

build:
  merge_build_host: True  # [win]
  number: 1
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-dplyr >=0.7.0
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-snakecase >=0.9.2
    - r-tidyr >=0.7.0
  run:
    - r-base
    - r-dplyr >=0.7.0
    - r-magrittr
    - r-purrr
    - r-rlang
    - r-snakecase >=0.9.2
    - r-tidyr >=0.7.0

test:
  commands:
    - $R -e "library('janitor')"           # [not win]
    - "\"%R%\" -e \"library('janitor')\""  # [win]

about:
  home: https://github.com/sfirke/janitor
  license: MIT
  summary: 'The main janitor functions can: perfectly format data.frame column names; provide
    quick counts of variable combinations (i.e., frequency tables and crosstabs); and
    isolate duplicate records. Other janitor functions nicely format the tabulation
    results. These tabulate-and-report functions approximate popular features of SPSS
    and Microsoft Excel. This package follows the principles of the "tidyverse" and
    works well with the pipe function %>%. janitor was built with beginning-to-intermediate
    R users in mind and is optimized for user-friendliness. Advanced R users can already
    do everything covered here, but with janitor they can do it faster and save their
    thinking for the fun stuff.'
  license_family: MIT

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: janitor
# Title: Simple Tools for Examining and Cleaning Dirty Data
# Version: 1.2.0
# Authors@R: c(person("Sam", "Firke", email = "samuel.firke@gmail.com", role = c("aut", "cre")), person("Bill", "Denney", email = "wdenney@humanpredictions.com", role = "ctb"), person("Chris", "Haid", email = "chrishaid@gmail.com", role = "ctb"), person("Ryan", "Knight", email = "ryangknight@gmail.com", role = "ctb"), person("Malte", "Grosser", email = "malte.grosser@gmail.com", role = "ctb"))
# Description: The main janitor functions can: perfectly format data.frame column names; provide quick counts of variable combinations (i.e., frequency tables and crosstabs); and isolate duplicate records. Other janitor functions nicely format the tabulation results. These tabulate-and-report functions approximate popular features of SPSS and Microsoft Excel. This package follows the principles of the "tidyverse" and works well with the pipe function %>%. janitor was built with beginning-to-intermediate R users in mind and is optimized for user-friendliness. Advanced R users can already do everything covered here, but with janitor they can do it faster and save their thinking for the fun stuff.
# URL: https://github.com/sfirke/janitor
# BugReports: https://github.com/sfirke/janitor/issues
# Depends: R (>= 3.1.2)
# Imports: dplyr (>= 0.7.0), tidyr (>= 0.7.0), snakecase (>= 0.9.2), magrittr, purrr, rlang
# License: MIT + file LICENSE
# LazyData: true
# RoxygenNote: 6.1.1
# Suggests: testthat, knitr, rmarkdown, sf, tibble
# VignetteBuilder: knitr
# Encoding: UTF-8
# NeedsCompilation: no
# Packaged: 2019-04-21 03:59:05 UTC; sam
# Author: Sam Firke [aut, cre], Bill Denney [ctb], Chris Haid [ctb], Ryan Knight [ctb], Malte Grosser [ctb]
# Maintainer: Sam Firke <samuel.firke@gmail.com>
# Repository: CRAN
# Date/Publication: 2019-04-21 04:20:13 UTC
