travis:
  secure:
    BINSTAR_TOKEN: KRyVpKCZug6NC4tikstAhBwbp6bcYYrmCrupSM60wxMoxQqiQVDhdl563DNGQLJvVIM2HsrzR/AuD5ZBsvTXIka5f20Ft+6Up4vrGbs4kRSjx8/QXL6ksm0Q+rOOeW6HObE43bAKaSE/Cq9y6C9NqtbMggoLI9MB/A1AD+A6UbskAdOr2/j1ZhroXmsjqdyHSuuOqo+LwBo+ZGINzSPGVM9SAIqiKyGTReGlbS1IWftWSK7L9mPl636qYfvu0eu7rBtdG1O3/e0M8ioVySuEuUvQCZZ15r3z+gSeSS4KXjAAdG9vXETFIE3x7sYo+yrE6laAJzb2UxJ6IXQt5LB1tZun2U3e9Kxou6RtUdCGl1uGA6+CqHGwEEP7sla7UnfvTLyvpej3JlwVdoYUe49NoMGvHymmFQRLX2mLxLWe5X+EqMeyf1DYUAmPMOcDGdCQ9D5omKgRY3ZauqOoRfdXQwp6bGPkhtA/c2TmpuoKqk8dVt7pIQzbq1OIcL8vM4uhzdgdW2V2IL1rMPLXLE8dD2s1oCd1mA/3vVa1dgoyCp25ZVGUIQnhkXnzMozydWzm+dxeon5kH+/V35FV5JFCeoLnBX/ALgcad+8G6Et5IWkhyP/DmjIZUP8lhwgGegZqZC8tZm2htzhfW86I4EYhQS1837zdPCwcJtndAMCXh5U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
