appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: RHXO7EP85EA7yZuGjNWZ0HObFKtrV411QjgFXXmbxOXmWr+7UcWdEJdQK/T3o5dlSTDNAk8CJQGdwFiD20nOKtPNGEfgrD6CvT7CocJ1x1maw0MfH6PFHdmwoSiYwPCTfyGdYHPYkVCXCtQL9QLOGls2EcVJ6gBuBTOZKye1Gwi5rb0bm8c5nT4DG2nVrTIYflrB1+8Lqv1iOxjNx+xeDnwqn1a5AF9zrkweOqkkNC/L6+N8tAyAdsUpRKUrRuyTIq9x/ykvPKbeAr12haSC6kURhTkI9qGpjJddqnWDBZqbZNbtENkbT6AvICCJGsAt9Vu8aJNtRIM+NnJnH95yDB6LdZRtGkhiocSFWIlB41l04tqw2tN9gJF0Z3PVhuj6BDhvpMpkYC4vaKcmxrlxOV6mEHhn27ersQKLZbjrE/LOvIkU6JkJa6xOen3VCu4uD9NCQFos4+MAMqvhy+NZFyceCujgb+l+9kneDovlblmfkdgDTcVAxIjMHbPcSSSo9RIRrdS2KbZQqR8kS/gZJXjgKWgq9idlLRK5c+RDTVxC6DSQXi96LliWcObjgbjXVgwh/HrYI/Awad+mRgsMolQByaCnPEJUF7Z1M/eA0fCwVayTpIZ1oJQKJnpjglSBjiF91ZISsU5yXDy6LnasxU16/eRdjMUSsNObGMsTVy4=
conda_forge_output_validation: true
