travis:
  secure:
    BINSTAR_TOKEN: oJPejQXqsZVozu+7SWCkNExaa5r+E1wCWWUs9HrmwTz2BBv77SLimZ4HZfdT8OfxEh4lddvmb23wekLmpLNpmIGjNbdK2aDQep2TGqcV7VbnESs9AMSaqWejGCDxswvoW3+ZQqBeYuFMvryyzlIf5UVfY8wPS7X89PvUgdhXqxAKNEUhA24xRNAo8Ds+VoR6IRyKmSRXC06AYQXFlxp7PDgX4pZ6aVb9+7o8AN6GjIykZ9P8tvWz/jF2aePXDqsQ3WAo50QjO+/wh+2h/DcXf4XkZVyv3/TTvlEiOXfpFEUJEEzpqH/ANp0Zil/+8qnKxiQY57G5C0q7Zu/uV88gHevDFcHOZc3ihjrcTlAMRVV1eWDKl5ElAP1vs6xBG2/SqLhnphO+QgHs9lnjLIOVKMpu03mdmrB31YfBaJLVgTizYEFtm2E2viO75q0yuws1Ulf3I/AUwWSvLCtVSeFKzY3hh7s9Y5FsrSsFusuSkLGP4D1r0jC4RpbjgTLPzYRTgufAZttuw4cPj0zqYvOZqiA3XmZUVfU604qY0p75ZGRNtJ+I/x2xBWgzXL3QkUaBHM1o7QpdGro/Xk8mD6hopya2bpq4cqRFtQWwBkG5d563+GHC4moX2UDnLQNtkAyQyQOI77qc9mdgwCd8Ws50/vL5HRhMzm30HuZWPyibufw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
