travis:
  secure:
    BINSTAR_TOKEN: PQ81ozIZRWTxMRAjLQpsmsu3zwVb40C6agk/G+/+A9Gq96fgDPCoTe02FchwslKztuvk2kw2jVQWm2L2i/Q1MpGBqdolQu94m9bQ7vjSiKYnjMH8o+8AvkPM5fIfzOIKT4ENmpSCqNxH+VcqabVQI9yr9B7SMAzPPE3nvr0A0yWsCOZxHE/BgYBUq0MEnEiriQD4L8/8SZNO93PmRNwKHlV+uzP64pFKpmY8pbQjgPpt6YgeKSNKz+m6p2AqZnmFzi9IU9sW94v543mVHSUJW+9arterPrlMElBIjCLqkGHX9Ehl356voOEzNuTOBIhZuEfUgS9bgn124FTbpYhCDtgYJq55yZFZOYQclkmRAmyx9MU04wHTieNoREL3UV2klqZoJqqCVVv77KoCrkQTzh5qM6cOM5hmJOny2dt//t/Sbn7jH4WhE2CBuoP58K59U9g583a7yEmLC51WdJXrP7nAOLamux9SButtUyUMqYFOMcxjpuinqfqYyldGKbSdPl/EX/8qv8f31tTQBRSHOTqKXjIgpCtBlPUCn4/1mjeOEkU4+9hycgjxLolJ9PqXFx3XKRWtAy5aCbgQuQAfo+CYW97mjktUS/laTlhlJCYT9QvMDOgR4xkBpPWEfIGYRUDwkTQqXbkpV13IFfTD4vwrWL1oj4+QNw54W8atQfg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
